### ISSUE TITLE
Lets develop client architecture

### ISSUE THREAD

**Issue by SvyatoslavFedynyak** [SvyatoslavFedynyak/Galagram#1]

**Comment by iamprovidence** [comment]
It is the same as we have done previous architecture?

**Comment by SvyatoslavFedynyak** [comment]
> 
> 
> It is the same as we have done previous architecture?
>
What is that previous?

**Comment by iamprovidence** [comment]
All the previous architecture, I mean. But dont worty, I already got this

**Comment by iamprovidence** [comment]
class User
{
   int ID {get;set}
   string Name {get;set}
   string Surname{get;set}
   string Nickname{get;set}
   string password{get;set}
   bool IsAdmin {get;set;}
   ICollection<Desk> {get;set;}
   ICollection<Message> {get;set;}
}
class Message
{
  int ID{get;set;}
   int UserId{get;set;}
  string Text{get;set;}
  DateTime Time {get;set;}
}
class Theme
{
   int ID {get;set}
   string Name {get;set}
   Color BackgroundColor {get;set}
   Color ColumnColor {get;set}
   ICollection<Desk> {get;set;}   
}
class Desk
{
  int ID {get;set}
  int AdminId{get;set;}
  int UserId{get;set}
  int ThemeId{get;set}
  string Name {get;set}
  double PercentageDone {get;set;}
  ICollection<Conversation> {get;set;}   
  ICollection<Comments> {get;set;}   

}
class Conversation
{
  int ID {get;set}
  string Name {get;set}
  string Text{get;set}
  int DeskId{get;set;}  
  ICollection<ConversationComment > {get;set;}   
  Voting Voting{get;set;}
}
class Voting
{
  int ID{get;set;}
  int ConversationId{get;set;}
  int UserId{get;set;}
  bool VoteYes{get;set;}
  bool VoteNo{get;set;}
  bool VoteDontKnow{get;set;}
}
class Column
{
  int ID {get;set}
  string Name {get;set}
  int DeskId{get;set}

}

class ToDo
{
  int ID {get;set}
  int CardID {get;set}
  Color Color {get;set}
  string Text{get;set}
  string Header{get;set}
  DateTime Deadline{get;set}
  ICollection<ToDoComment > {get;set;}   

}
class Category
{
  int ID {get;set}
  string Name {get;set}
  Color Color {get;set}
}
class Comments
{
  int ID {get;set}
  string Text{get;set}
  DateTime Date{get;set}
  ICollection<Like>{get;set;}
}
class ToDoComment : Comments
{
   int ToDoId{get;set}
}
class ConversationComment : Comments
{
   int ConversationId{get;set}
}
class Like
{
  int ID{get;set}
  int UserId{get;set;}
  int CommentsId{get;set;}
}

**Comment by SvyatoslavFedynyak** [comment]
So what about new architecture?

**Comment by iamprovidence** [comment]
@Lenkelheit  will send it to you later
