### ISSUE TITLE
Let's divide the tasks

### ISSUE THREAD

**Issue by SvyatoslavFedynyak** [SvyatoslavFedynyak/Galagram#12]
Design:
- [x] Windows

Implementation require:

Models:
- [x] Like
- [x] Subject
- [x] Photo
- [x] User
- [x] Comment
- [x] Message

ViewModels:
- [x] HomeVM
- [x] SearchVM
- [x] SignUpVM
- [x] QuestionVM
- [x] PhotoVM
- [x] SettingsVM
- [x] FollowersVM

Data Base Access:
- [x] AppContext
- [x] UnitOfWork
- [x] GenericRepository

Test:

Models:
- [x] Like
- [x] Subject
- [x] Photo
- [x] User
- [x] Comment
- [x] Message

ViewModels:
- [x] HomeVM
- [x] SearchVM
- [x] SignUpVM
- [x] QuestionVM
- [x] PhotoVM
- [x] SettingsVM
- [x] FollowersVM

Data Base Access:
- [x] AppContext
- [x] UnitOfWork
- [x] GenericRepository

**Comment by iamprovidence** [comment]
Windows, I guess

**Comment by SvyatoslavFedynyak** [comment]
DataBase Accsess

**Comment by Lenkelheit** [comment]
Ok, I take a ViewModels.
