### ISSUE TITLE
Application type

### ISSUE THREAD

**Issue by SvyatoslavFedynyak** [SvyatoslavFedynyak/Galagram#3]
My proposition is:
Client - Windows Forms
Server - Console App

**Comment by iamprovidence** [comment]
@SvyatoslavFedynyak , I am lit of bit confused. Why do we use Windows Forms and Console if it should be written on WPF

**Comment by SvyatoslavFedynyak** [comment]
@iamprovidence 
Oh, i didnt know about it. But anyway we don't need WPF for server.

**Comment by iamprovidence** [comment]
@SvyatoslavFedynyak , can you explain me? How will server work, and what is it? Because how I see it, that we have Data Base, and each user can modify it. that all....

**Comment by SvyatoslavFedynyak** [comment]
@iamprovidence 
1. Client and server should be different aplications, that can start and work regaldless from each other.
2. Yes, i forgot about Data Base. Will we use MS SQL Server for it? Because i dont know anything about Entity and CodeFirst.

**Comment by iamprovidence** [comment]
> 1. Client and server should be different aplications, that can start and work regaldless from each other.

For real? Can you give me an example how they can work separately in our task?



> 2\. Yes, i forgot about Data Base. Will we use MS SQL Server for it? Because i dont know anything about Entity and CodeFirst.

I have no idea either

**Comment by SvyatoslavFedynyak** [comment]
@iamprovidence  
1. I'll explain it on lesson. 
2. So how we will do it then?

**Comment by iamprovidence** [comment]
What about :
server — Windows Form
client — WPF

**Comment by SvyatoslavFedynyak** [comment]
> What about :
> server — Windows Form
> client — WPF
>
