### ISSUE TITLE
Create config class

### ISSUE THREAD

**Issue by iamprovidence** [SvyatoslavFedynyak/Galagram#33]
Yo, folks, I think w should have config class for main configuration as follow
* program name
* photo save path
* avatar save path
* messages
and so on

**Comment by SvyatoslavFedynyak** [comment]
>
>     * photo save path
> 
This OK, but all the other data should save in DB...

**Comment by iamprovidence** [comment]
For what reason?

**Comment by iamprovidence** [comment]
It was just a request....But I am happy that already done it
