### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by iamprovidence** [SvyatoslavFedynyak/Galagram#5]
We already have user story and ER-diagram can we save it here in github?
Also will there be some directory hierarchy for better project understanding?

**Comment by SvyatoslavFedynyak** [comment]
> 
> 
> We already have user story and ER-diagram can we save it here in github?
> Also will there be some directory hierarchy for better project understanding?
>
On weekends ok?
In all case, if it won't be client-server, you can upload some files by yourself
