### ISSUE TITLE
Mistakes on GitHub

### ISSUE THREAD

**Issue by iamprovidence** [SvyatoslavFedynyak/Galagram#8]
Wrong project name. Shoulb be "Galagram"
Readme File is incorrect
Add_model_plan is incorrect
Wrong project name
* what is DataControl? what the data doest is t control?
* Galagram project has "MainWindow" it should not be there since all windows are in other projects. App.xaml should have correct StartupUri
* what is InstancesLibrary? Is it **Entities**? It could has more that only Entities. What about Models?  Also **_Library** in name is redundancy
* UserControl? What? The worst name for library I have ever seen. Can we rename it to ViewModels?
* WindowsUserControl? What about View? So now we can easily see MVVM structure of the project

**Comment by SvyatoslavFedynyak** [comment]
> 
> Wrong project name. Shoulb be "Galagram"
>
Done
>
> Readme File is incorrect
>
I don't know how to write readme
>
> Add_model_plan is incorrect
> 
What should i do with it?
>
> Wrong project name
> 
Done
>
>     * what is DataControl? what the data doest is t control?
> 
Done
>
>     * Galagram project has "MainWindow" it should not be there since all windows are in other projects. App.xaml should have correct StartupUri
>
Don't know how to put correct id, else done
> 
>     * what is InstancesLibrary? Is it **Entities**? It could has more that only Entities. What about Models?  Also **_Library** in name is redundancy
> 
Done
>
>     * UserControl? What? The worst name for library I have ever seen. Can we rename it to ViewModels?
> 
Done
>
>     * WindowsUserControl? What about View? So now we can easily see MVVM structure of the project
>
Done

**Comment by iamprovidence** [comment]
> Done

Repository still has bad name


> I don't know how to write readme

Now its fine. Dont worry


> What should i do with it?

Delete?

> Don't know how to put correct id, else done

Ok, I will do it myself later

**Comment by SvyatoslavFedynyak** [comment]
> 
> Repository still has bad name
> 
Done
> 
> Delete?
> 
Done
