### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iamprovidence** [SvyatoslavFedynyak/Galagram#9]
What you think if we had a board for each project?

**Comment by SvyatoslavFedynyak** [comment]
6 boards? Omg, why did I take it...

**Comment by iamprovidence** [comment]
Why not? Its just a suggestion. Will be easier to track the progress on every project, also an special issues for each project that has check boxes will be nice

**Comment by SvyatoslavFedynyak** [comment]
> 
> Why not? Its just a suggestion. Will be easier to track the progress on every project, also an special issues for each project that has check boxes will be nice
>
This project isn't much bigger than 5 task, that we easily did with 1 board
